# 使用str()将指定数据转换为字符串
# reasult1=str(12)
# reasult2=str( 12 )
# reasult3=str(12000)
# reasult4=str(1.8e3)
# print(type(reasult1),reasult1)
# print(type(reasult2),reasult2)
# print(type(reasult3),reasult3)
# print(type(reasult4),reasult4)
# 使用in()将指定数据转换为整型
# reasult1=int(15.6)
# reasult2=int(   12   )
# reasult3=int('123')
# reasult4=int(12)
# print(type(reasult1),reasult1)
# print(type(reasult2),reasult2)
# print(type(reasult3),reasult3)
# print(type(reasult4),reasult4)
# 使用float()将指定数据转换为浮点型
reasult1=float(15.6)
reasult2=float(   12   )
reasult3=float('123')
reasult4=float('15.6')
print(type(reasult1),reasult1)
print(type(reasult2),reasult2)
print(type(reasult3),reasult3)
print(type(reasult4),reasult4)
